//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banco
    {
        public int IdBanco { get; set; }
        public string Descripcion { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string Fax { get; set; }
        public string Apartado { get; set; }
        public string Correo { get; set; }
        public string Cuenta { get; set; }
    }
}
