//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Caja
    {
        public Caja()
        {
            this.PagosCajas = new HashSet<PagosCaja>();
            this.SaldoCajas = new HashSet<SaldoCaja>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public int IdCaja { get; set; }
        public string Descripcion { get; set; }
        public bool Disponible { get; set; }
        public int IdUsuario { get; set; }
        public int Consecutivo { get; set; }
        public bool UsaConsecutivoGlobal { get; set; }
        public bool GuardadoAutomatico { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<PagosCaja> PagosCajas { get; set; }
        public virtual ICollection<SaldoCaja> SaldoCajas { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
