//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credito
    {
        public int IdCredito { get; set; }
        public int IdCliente { get; set; }
        public int IdLinea { get; set; }
        public string Descripcion { get; set; }
        public decimal Tasa { get; set; }
        public decimal Cuota { get; set; }
        public int Plazo { get; set; }
        public decimal MontoInicial { get; set; }
        public decimal SaldoActual { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<System.DateTime> FechaProximoPago { get; set; }
        public Nullable<System.DateTime> FechaUltimoPago { get; set; }
        public Nullable<System.DateTime> FechaUltimoAbono { get; set; }
        public int IdUsuario { get; set; }
        public int Consecutivo { get; set; }
        public int Referencia { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual LineasCredito LineasCredito { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
