//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class FrecuenciasPago
    {
        public FrecuenciasPago()
        {
            this.Clientes = new HashSet<Cliente>();
        }
    
        public int IdFrecuenciaPago { get; set; }
        public string Descripcion { get; set; }
        public int DiasPorYear { get; set; }
        public int DiasPorPeriodo { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
    }
}
