//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineasCredito
    {
        public LineasCredito()
        {
            this.Creditos = new HashSet<Credito>();
        }
    
        public int IdLineaCredito { get; set; }
        public string Descripcion { get; set; }
        public bool Activa { get; set; }
        public int Consecutivo { get; set; }
        public decimal Tasa { get; set; }
        public decimal TasaMora { get; set; }
        public int DiasMora { get; set; }
        public int Plazo { get; set; }
        public bool Refunde { get; set; }
        public int Cuotas { get; set; }
        public decimal MontoMaximo { get; set; }
        public int PlazoMaximo { get; set; }
    
        public virtual ICollection<Credito> Creditos { get; set; }
    }
}
