//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ControlEntities : DbContext
    {
        public ControlEntities()
            : base("name=ControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Banco> Bancos { get; set; }
        public virtual DbSet<Tarjeta> Tarjetas { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Credito> Creditos { get; set; }
        public virtual DbSet<FrecuenciasPago> FrecuenciasPagoes { get; set; }
        public virtual DbSet<LineasCredito> LineasCreditoes { get; set; }
        public virtual DbSet<Bitacora> Bitacoras { get; set; }
        public virtual DbSet<NumericType> NumericTypes { get; set; }
        public virtual DbSet<ParametrosGeneral> ParametrosGenerals { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
        public virtual DbSet<Existencia> Existencias { get; set; }
        public virtual DbSet<Producto> Productos { get; set; }
        public virtual DbSet<UnidadesMedida> UnidadesMedidas { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<Caja> Cajas { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVentas { get; set; }
        public virtual DbSet<Pago> Pagos { get; set; }
        public virtual DbSet<PagosCaja> PagosCajas { get; set; }
        public virtual DbSet<ParametrosVenta> ParametrosVentas { get; set; }
        public virtual DbSet<SaldoCaja> SaldoCajas { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
    }
}
