//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class NumericType
    {
        public int @int { get; set; }
        public Nullable<decimal> numeric { get; set; }
        public Nullable<decimal> @decimal { get; set; }
        public Nullable<double> @float { get; set; }
        public Nullable<decimal> money { get; set; }
        public Nullable<float> real { get; set; }
        public decimal numericN { get; set; }
        public decimal decimalN { get; set; }
        public double floatN { get; set; }
        public decimal moneyN { get; set; }
    }
}
