//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public int IdPago { get; set; }
        public int ConsecutivoVentas { get; set; }
        public int IdCaja { get; set; }
        public string FormaPago { get; set; }
        public int IdLinea { get; set; }
        public int IdBanco { get; set; }
        public int IdTarjeta { get; set; }
        public string NumeroChequeTarjeta { get; set; }
        public decimal MontoRecibido { get; set; }
        public decimal MontoAplicado { get; set; }
        public string Estado { get; set; }
    }
}
