//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PagosCaja
    {
        public int IdCaja { get; set; }
        public string FormaPago { get; set; }
        public int IdPagoCaja { get; set; }
    
        public virtual Caja Caja { get; set; }
    }
}
