//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Existencias = new HashSet<Existencia>();
            this.DetalleVentas = new HashSet<DetalleVenta>();
        }
    
        public int IdProducto { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public int IdProveedor { get; set; }
        public decimal PrecioUnitario { get; set; }
        public decimal PrecioVenta { get; set; }
        public int IdCategoria { get; set; }
        public Nullable<decimal> Minimo { get; set; }
        public decimal Impuestos { get; set; }
        public int IdUnidadMedida { get; set; }
        public bool VerificaDisponible { get; set; }
        public decimal Descuento { get; set; }
        public decimal Utilidad { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Existencia> Existencias { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
        public virtual Proveedore Proveedore { get; set; }
        public virtual UnidadesMedida UnidadesMedida { get; set; }
    }
}
