//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaldoCaja
    {
        public int IdSaldoCaja { get; set; }
        public int IdCaja { get; set; }
        public decimal SaldoEfectivo { get; set; }
        public decimal SaldoDocumentos { get; set; }
        public decimal MontoInicial { get; set; }
    
        public virtual Caja Caja { get; set; }
    }
}
