//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnidadesMedida
    {
        public UnidadesMedida()
        {
            this.Productos = new HashSet<Producto>();
        }
    
        public int IdUnidadMedida { get; set; }
        public string Descripcion { get; set; }
        public string NombreCorto { get; set; }
    
        public virtual ICollection<Producto> Productos { get; set; }
    }
}
