//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Creditos = new HashSet<Credito>();
            this.Cajas = new HashSet<Caja>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public int IdUsuario { get; set; }
        public string Nombre { get; set; }
        public bool Administrador { get; set; }
        public string Clave { get; set; }
        public bool Activo { get; set; }
        public bool Mantenimientos { get; set; }
        public bool Procesos { get; set; }
        public bool Reportes { get; set; }
        public bool Otros { get; set; }
        public bool Consultas { get; set; }
    
        public virtual ICollection<Credito> Creditos { get; set; }
        public virtual ICollection<Caja> Cajas { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
