//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ControlEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.DetalleVentas = new HashSet<DetalleVenta>();
        }
    
        public int IdVenta { get; set; }
        public int Consecutivo { get; set; }
        public System.DateTime Fecha { get; set; }
        public int IdUsuario { get; set; }
        public decimal TotalVenta { get; set; }
        public int IdCaja { get; set; }
        public int IdCliente { get; set; }
        public decimal TotalImpuestos { get; set; }
        public decimal TotalDescuentos { get; set; }
        public string Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Caja Caja { get; set; }
        public virtual ICollection<DetalleVenta> DetalleVentas { get; set; }
    }
}
